all: clear build
	@echo "HOLA"

build: 
	@echo "I am buiding here"

clear:
	@echo "I clear before build"
	
test:
	@echo "do the tests"


tee:
	@echo "need tee"


beer:
	@echo "i prefer beeer"


tequila:
	@echo "give me tequila"


foo-verbose:
	echo "I will build and do everything ok" && echo "i fix the problem"  && echo "the end" 

foo:
	@echo "I will build and do everything ok" && echo "i fix the problem"  && echo "the end" 

foo-error:
	@echo "I will build and do everything ok" && false  && echo "the end" 
