all: clear build
	@echo "HOLA"

build: 
	@echo "I am buiding here"

clear:
	@echo "I clear before build"
	
test:
	@echo "do the tests"


tee:
	@echo "need tee"


beer:
	@echo "i prefer beeer"


tequila:
	@echo "give me tequila"
